### ISSUE TITLE
IllegalArgumentException: Pointer index out of range

### ISSUE THREAD

**Issue by silviahisham** [ppamorim/Dragger#51]
Hello, I get this error randomly in my log files, do you have any idea why does it happen?
Thanks.

> Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range pointerIndex=-1 pointerCount=1
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2072)
       at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
       at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:110)
       at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:462)
       at com.github.ppamorim.dragger.ViewDragHelper.processTouchEvent(ViewDragHelper.java:1161)
       at com.github.ppamorim.dragger.DraggerView.onTouchEvent(DraggerView.java:198)
       at android.view.View.dispatchTouchEvent(View.java:9399)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2549)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2469)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1785)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2867)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2430)
       at android.view.View.dispatchPointerEvent(View.java:9619)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4471)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4337)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3869)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3922)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3888)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4014)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3896)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4071)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3869)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3922)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3888)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3896)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3869)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6170)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6144)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6105)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6286)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6244)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6317)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:886)
       at android.view.Choreographer.doCallbacks(Choreographer.java:698)
       at android.view.Choreographer.doFrame(Choreographer.java:627)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5665)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

**Comment by saqibatiq** [comment]
Same issue, still no answer :(
